package main

import (
	"encoding/json"
	"fmt"
	"github.com/bwmarrin/snowflake"
	"io/ioutil"
	"net/http"
	"strings"
	"sync"
	"time"
)

var TestUrl = "http://74ab25e1merchant.cwallet.com/ccpayment/v1/pay/CreateTokenTradeOrder"

func main() {

	bill := BillId()
	jsonContent := &JsonContent{
		TokenId:    "e8f64d3d-df5b-411d-897f-c6d8d30206b7",
		Chain:      "BSC",
		Amount:     "1",
		Contract:   "0x2170ed0880ac9a755fd29b2688956bd959f933f8",
		OutOrderNo: bill,
		FiatName:   "USD",
	}
	//content, _ := json.Marshal(jsonContent)
	//timestamps := int64(1672261484)
	//times := strconv.Itoa(int(timestamps))
	//randStr := util.RandStr(5)
	//serviceStr := "merchant_id=" + mchid + "&appid=" + arr.Appid + "&json_content=" + string(content) + "&timestamp=" + times + "&noncestr=" + randStr
	serviceStr := "merchant_id=10001&appid=202211181420251593489282956267520&json_content={\"token_id\":\"e8f64d3d-df5b-411d-897f-c6d8d30206b7\",\"chain\":\"BSC\",\"amount\":\"1\",\"contract\":\"0x2170ed0880ac9a755fd29b2688956bd959f933f8\",\"out_order_no\":\"" + bill + "\",\"fiat_name\":\"USD\"}&timestamp=1672299548&noncestr=ylaDo"
	fmt.Println(serviceStr)
	bt, err := RsaSignWithSha256([]byte(serviceStr), []byte(PrivateKey))
	if err != nil {
		fmt.Println("Sign err:", err)
		return
	}
	req := &SubmitCreateTradeOrderRequest{
		MerchantId:  int64(10001),
		Appid:       "202211181420251593489282956267520",
		Timestamp:   1672299548,
		JsonContent: jsonContent,
		Sign:        bt,
		NotifyUrl:   "http://127.0.0.1:8000/pay/notify",
		Remark:      "",
		Device:      "app",
		Noncestr:    "ylaDo",
	}
	bytes, _ := json.Marshal(req)
	response, err := http.Post(TestUrl, "application/json", strings.NewReader(string(bytes)))
	if err != nil {
		fmt.Println("err:", err.Error())
		return
	}
	if response.StatusCode == http.StatusOK {
		body, _ := ioutil.ReadAll(response.Body)
		obj := AutoGenerated{}
		err = json.Unmarshal(body, &obj)
		if err != nil {
			fmt.Println(err)
			return
		}
	}

}

func BillId() string {
	return fmt.Sprintf("%s%d",
		Format(time.Now(), CompactLayout),
		GlobalSnowflakeNode().Generate().Int64())
}

func InitGlobalSnowflakeNode(nodeId int64) (err error) {
	globalSnowflakeNodeSync.Do(func() {
		globalSnowflakeNode, err = snowflake.NewNode(nodeId)
	})

	return err
}

func GlobalSnowflakeNode() *snowflake.Node {
	if globalSnowflakeNode == nil {
		if err := InitGlobalSnowflakeNode(1); err != nil {
			panic(err)
		}
	}

	return globalSnowflakeNode
}

func Format(t time.Time, layout ...string) string {
	if len(layout) != 0 {
		return t.Format(layout[0])
	}
	return t.Format(DefaultLayout)
}

var (
	globalSnowflakeNode     *snowflake.Node
	globalSnowflakeNodeSync sync.Once
)

const CompactLayout = "20060102150405"
const DefaultLayout = "2006-01-02 15:04:05"

type AutoGenerated struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data Data   `json:"data"`
}

type Data struct {
	BillID      string `json:"bill_id"`
	RedirectUrl string `json:"redirect_url"`
}
